/*
 * Copyright (c) 2021, J2 Innovations. All Rights Reserved
 */

import { Node } from './Node'

const DATE_OPTIONS: Intl.DateTimeFormatOptions = {
	year: '2-digit',
	month: '2-digit',
	day: '2-digit',
	hour: '2-digit',
	minute: '2-digit',
	second: '2-digit',
}

/**
 * Generates a comment block for a document.
 */
export class DocCommentNode implements Node {
	public readonly newLines = 1

	public generateCode(out: (code: string) => void): void {
		out('/*')
		out(
			` * Automatically generated by haystack-codegen on ${this.toDateString()}.`
		)
		out(' */')
	}

	public toDateString(): string {
		return new Date().toLocaleDateString(undefined, DATE_OPTIONS)
	}
}
